
package gui;

import utils.Validators;
import javax.swing.JOptionPane;
import Listeners.CreateAccountListener;
import social.User;
import utils.Messages;

/**
 * Panel with create account fields
 * @author bmvin
 */
public class CreateAccountPanel extends javax.swing.JPanel {

    private CreateAccountListener listener;

    /**
     * Creates new form CreateAccountPanel
     */
    public CreateAccountPanel() {
        initComponents();
    }

    /**
     * Set CreateAccountListener to send the information to the parent component.
     * @param listener
     */
    public void setListener(CreateAccountListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordConfirmationLabel = new javax.swing.JLabel();
        passwordConfirmationField = new javax.swing.JPasswordField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        nameLabel.setText("Full Name:");

        emailLabel.setText("Email:");

        passwordLabel.setText("Password:");

        passwordConfirmationLabel.setText("Password Confirmation:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(emailField)
                    .addComponent(passwordField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(emailLabel)
                            .addComponent(passwordLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                            .addComponent(passwordConfirmationLabel))
                        .addGap(0, 261, Short.MAX_VALUE))
                    .addComponent(passwordConfirmationField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordConfirmationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Validate the inputs
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        String name = "", email = "", password = "", passwordConfirmation = "";
        String warnings = "";

        // name validation
        name = nameField.getText().trim();
        if (!Validators.checkNotEmptyStringNotNull(name)) {
            warnings += Messages.EMPTY_NAME_ERROR;
        }

        // validate email
        email = emailField.getText().trim();
        if (!Validators.validEmail(email)) {
            warnings += Messages.INVALID_EMAIL_ERROR;
        }

        // validate password
        password = new String(passwordField.getPassword()).trim();
        if (!Validators.checkNotEmptyStringNotNull(password)) {
            warnings += Messages.EMPTY_PASSWORD_ERROR;
        }

        // validate confirm password
        passwordConfirmation = new String(passwordConfirmationField.getPassword()).trim();
        if (!Validators.checkNotEmptyStringNotNull(passwordConfirmation)) {
            warnings += Messages.EMPTY_PASSWORD_CONFIRMATION_ERROR;
        }
        if (!Validators.passwordsMatches(password, passwordConfirmation)) {
            warnings += Messages.PASSWORDS_DONT_MATCH_ERROR;
        }

        if (!warnings.isEmpty()) {
            JOptionPane.showMessageDialog(this, warnings, Messages.CREATE_ACCOUNT_ERROR, JOptionPane.WARNING_MESSAGE);
        } else {
            // everything is great
            User user = new User(name, email);
            listener.sendUser(user, password);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // CLEAR ALL FIELDS
        clearFields();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Clear all input fields
     */
    public void clearFields() {
        nameField.setText("");
        emailField.setText("");
        passwordField.setText("");
        passwordConfirmationField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordConfirmationField;
    private javax.swing.JLabel passwordConfirmationLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables
}
