/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import social.Database;
import social.Group;
import social.User;

/**
 *
 * @author bmvin
 */
public class GroupBlockedUsersDialog extends javax.swing.JDialog {

    private Frame parentFrame;
    private User currentUser;
    private Group currentGroup;
    private final Database db;

    /**
     * Creates new form GroupBlockedUsersDialog
     *
     * @param parent
     * @param modal
     * @param currentUser
     * @param currentGroup
     * @param db
     */
    public GroupBlockedUsersDialog(java.awt.Frame parent, boolean modal, User currentUser, Group currentGroup, Database db) {
        super(parent, modal);
        initComponents();
        this.currentUser = currentUser;
        this.currentGroup = currentGroup;
        this.parentFrame = parent;
        this.db = db;

        showInfo();
        setLocationRelativeTo(parentFrame);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        blockedList = new javax.swing.JList<>();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Blocked Users");

        blockedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        blockedList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blockedListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(blockedList);

        exitButton.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blockedListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blockedListMouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2 && list.getModel().getSize() != 0) {
            int index = list.locationToIndex(evt.getPoint());
            User selectedUser = (User) list.getModel().getElementAt(index);
            if (selectedUser != null) {
                if (!selectedUser.getUuid().equals(currentUser.getUuid())) {
                    GroupMember gm = new GroupMember(parentFrame, true, currentUser, selectedUser, currentGroup, db);
                }
            }
        }
        showInfo();

    }//GEN-LAST:event_blockedListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<User> blockedList;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void showInfo() {
        if (!(currentGroup.getBlocked().size() > 0)) {
            dispose();
        } else {
            populateList();

        }
    }

    private void populateList() {
        DefaultListModel<User> users = new DefaultListModel<>();

        for (String key : currentGroup.getBlocked()) {
            User u = this.db.getUserById(key);
            if (u != null) {
                users.addElement(u);
            }
        }

        blockedList.setModel(users);
    }
}
