package gui;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import social.Group;
import social.User;

/**
 * Group's requests list.
 *
 * @author bmvin
 */
public class GroupRequestsList extends javax.swing.JDialog {

    private final User currentUser;
    private final Group group;

    /**
     * Creates new form GroupRequestsList
     *
     * @param parent
     * @param modal
     * @param group
     * @param currentUser
     */
    public GroupRequestsList(java.awt.Frame parent, boolean modal, User currentUser, Group group) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        this.currentUser = currentUser;
        this.group = group;

        populateList();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestsList = new javax.swing.JList<>();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Group's Requests. Two clicks to accept request.");

        requestsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        requestsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(requestsList);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();

    }//GEN-LAST:event_closeButtonActionPerformed

    private void requestsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsListMouseClicked

        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2 && list.getModel().getSize() != 0) {
            int index = list.locationToIndex(evt.getPoint());
            User selectedUser = (User) list.getModel().getElementAt(index);
            if (selectedUser != null) {
                group.acceptRequest(currentUser, selectedUser);
                selectedUser.addGroup(group.getUuid());
            }
        }
        populateList();
    }//GEN-LAST:event_requestsListMouseClicked

    /**
     * Populate requests list.
     */
    private void populateList() {
        DefaultListModel<User> requests = new DefaultListModel<User>();
        for (User u : group.getRequests()) {
            if (u != null) {
                requests.addElement(u);
            }
        }

        requestsList.setModel(requests);

        if (!(group.numberRequests() > 0)) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<User> requestsList;
    // End of variables declaration//GEN-END:variables

}
