/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Listeners.EditBioListener;
import social.User;
import utils.Validators;

/**
 *
 * @author bmvin
 */
public class ProfilePanel extends javax.swing.JPanel {

    private User user;

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        this.user = user;
        initComponents();
        setVisible(true);

    }

    /*
     * @param user User's reference
    */
    public void setUser(User user) {
        if (user != null) {
            this.user = user;
            
            /* BIO AREA
             * Set up Edit Button Listener
            */
            bioArea.setEditable(false);
            EditBioListener listener = new EditBioListener(this.user, editBioButton, bioArea);
            editBioButton.addActionListener(listener);
            updateInfo();
        }
    }

    private void setNameLabel(String name) {
        if (!Validators.checkNotEmptyStringNotNull(name)) {
            nameLabel.setName(name);

        }
    }

    private void updateInfo() {
        setNameLabel(this.user.getName());
        // bio
        bioArea.setText(this.user.getBio());
        // profile pic goes here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bioArea = new javax.swing.JTextArea();
        editBioButton = new javax.swing.JToggleButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(750, 197));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("Vinicius Barbosa de Medeiros");

        imageLabel.setText("PROFILE PICTURE");

        bioLabel.setText("Bio:");

        bioArea.setColumns(20);
        bioArea.setRows(5);
        jScrollPane3.setViewportView(bioArea);

        editBioButton.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBioButton))
                    .addComponent(jScrollPane3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bioLabel)
                            .addComponent(editBioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bioArea;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JToggleButton editBioButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

}
