package gui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import social.User;
import utils.Validators;

/**
 *
 * @author bmvin
 */
public class ProfilePic extends javax.swing.JPanel {

    private User currentUser;
    private User targetUser;

    /**
     * Creates new form ProfilePic
     */
    public ProfilePic() {

        initComponents();
        showInfo();
    }

    public void setUsers(User current, User target) {
        this.currentUser = current;
        this.targetUser = target;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePicLabel = new javax.swing.JLabel();
        addProfilePicButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(125, 200));
        setMinimumSize(new java.awt.Dimension(125, 200));
        setPreferredSize(new java.awt.Dimension(125, 200));

        profilePicLabel.setMaximumSize(new java.awt.Dimension(62, 14));
        profilePicLabel.setMinimumSize(new java.awt.Dimension(62, 14));
        profilePicLabel.setPreferredSize(new java.awt.Dimension(62, 14));

        addProfilePicButton.setText("Add Pic");
        addProfilePicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfilePicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addProfilePicButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addProfilePicButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProfilePicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfilePicButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        this.targetUser.setProfilePicture(f.getAbsolutePath());
    }//GEN-LAST:event_addProfilePicButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProfilePicButton;
    private javax.swing.JLabel profilePicLabel;
    // End of variables declaration//GEN-END:variables

    private void showInfo() {
        if (currentUser != null && targetUser != null) {
            if (currentUser == targetUser) {
                String profilePic = targetUser.getProfilePic();
                if (Validators.checkNotEmptyStringNotNull(profilePic)) {
                    addProfilePicButton.setVisible(false);
                    // SET IMAGE
//                ImageIcon imageIcon = new ImageIcon(targetUser.getProfilePic());
//                Image img = imageIcon.getImage();
//                Image newImg = img.getScaledInstance(133, 175, java.awt.Image.SCALE_SMOOTH);
//                ImageIcon icon = new ImageIcon(newImg);
//
//                if (icon != null) {
//                    profilePicLabel.setIcon(icon);
//                    profilePicLabel.setText(null);
//                } else {
//                    profilePicLabel.setText("No Profile picture\n found!");
//                }
                } else {
                    addProfilePicButton.setVisible(true);
                }
            }
        }

    }
}
