/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import social.Database;
import social.User;

/**
 *
 * @author bmvin
 */
public class PublicProfile extends javax.swing.JDialog {

    private User targetUser;
    private User originUser;
    private Database db;

    /**
     * Creates new form PublicProfile
     */
    public PublicProfile(java.awt.Frame parent, boolean modal, User target, User origin, Database db) {
        super(parent, modal);
        initComponents();
        this.targetUser = target;
        this.originUser = origin;
        this.db = db;
        setLocationRelativeTo(parent);
        setTitle("Social App - " + this.targetUser.getName());
        nameLabel.setText(this.targetUser.getName());

        showInfo();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePic = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addFriendButton = new javax.swing.JButton();
        blockUserButton = new javax.swing.JButton();
        unblockUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        profilePic.setText("PROFILE PIC");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        addFriendButton.setText("Add as Friend");
        addFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendButtonActionPerformed(evt);
            }
        });

        blockUserButton.setText("Block User");
        blockUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockUserButtonActionPerformed(evt);
            }
        });

        unblockUserButton.setText("Unblock User");
        unblockUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unblockUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addFriendButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unblockUserButton)
                        .addGap(0, 227, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFriendButton)
                            .addComponent(blockUserButton)
                            .addComponent(unblockUserButton)))
                    .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInfo() {
        // already sent request

        // person block 
        if (this.originUser.userIsBlocked(this.targetUser.getUuid())) {
            blockUserButton.setVisible(false);
            addFriendButton.setVisible(false);
            unblockUserButton.setVisible(true);
        } else {
            if (this.targetUser.getRequests().contains(this.originUser.getUuid())) {
                addFriendButton.setVisible(false);
            } else {
                addFriendButton.setVisible(true);
            }
            blockUserButton.setVisible(true);
            unblockUserButton.setVisible(false);
        }
        // blocked by person
        if (this.targetUser.userIsBlocked(this.originUser.getUuid())) {
            addFriendButton.setVisible(false);
            blockUserButton.setVisible(false);
            unblockUserButton.setVisible(false);
        }
    }

    private void addFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendButtonActionPerformed
        // TODO add your handling code here:
        this.targetUser.sendRequest(this.originUser.getUuid());
        showInfo();
    }//GEN-LAST:event_addFriendButtonActionPerformed

    private void blockUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockUserButtonActionPerformed
        // TODO add your handling code here:
        this.originUser.blockUser(this.targetUser.getUuid());
        showInfo();
    }//GEN-LAST:event_blockUserButtonActionPerformed

    private void unblockUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unblockUserButtonActionPerformed
        // TODO add your handling code here:
        this.originUser.unblockUser(this.targetUser.getUuid());
        showInfo();
    }//GEN-LAST:event_unblockUserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendButton;
    private javax.swing.JButton blockUserButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel profilePic;
    private javax.swing.JButton unblockUserButton;
    // End of variables declaration//GEN-END:variables
}
